import {mkdir,rm,cp,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const ts=require('/opt/nvm/versions/node/v22.16.0/lib/node_modules/typescript/lib/typescript.js');
const root=process.cwd(), dist=path.join(root,'dist');
await rm(dist,{recursive:true,force:true});
await mkdir(path.join(dist,'assets'),{recursive:true});
await cp(path.join(root,'public'),dist,{recursive:true});
await cp(path.join(root,'index.html'),path.join(dist,'index.html'));
await cp(path.join(root,'src','styles.css'),path.join(dist,'assets','styles.css'));
let jsx=await readFile(path.join(root,'src','main.jsx'),'utf8');
jsx=jsx.replace("import React from 'react';\nimport './styles.css';\n",'');
const out=ts.transpileModule(jsx,{compilerOptions:{target:ts.ScriptTarget.ES2018,module:ts.ModuleKind.None,jsx:ts.JsxEmit.React,useDefineForClassFields:false,removeComments:false}});
if(out.diagnostics?.length) console.error(out.diagnostics.map(d=>ts.flattenDiagnosticMessageText(d.messageText,'\n')).join('\n'));
await writeFile(path.join(dist,'assets','app.js'),out.outputText);
const base='/mnt/data/psychologist-yaroslavl-react/dist/assets';
await cp(path.join(base,'react.production.min.js'),path.join(dist,'assets','react.production.min.js'));
await cp(path.join(base,'react-dom.production.min.js'),path.join(dist,'assets','react-dom.production.min.js'));
let html=await readFile(path.join(dist,'index.html'),'utf8');
html=html.replace('<script type="module" src="/assets/app.js"></script>','<link rel="stylesheet" href="/assets/styles.css"><script src="/assets/react.production.min.js"></script><script src="/assets/react-dom.production.min.js"></script><script src="/assets/app.js"></script>');
await writeFile(path.join(dist,'index.html'),html);
const hash=createHash('sha256').update(await readFile(path.join(dist,'assets','app.js'))).digest('hex');
await writeFile(path.join(dist,'version.json'),JSON.stringify({version:'3.0.0',appSha256:hash,runtime:'React 16.0.0 autonomous',transpiler:'TypeScript'},null,2));
